sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - txt2man
env: COMPILER=g++-6

language: cpp
compiler:
  - g++-6
before_script:
  - cmake ./sources
script:
  - make ./sources
  - ./sources/output/vcdMaker
