sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
env: COMPILER=g++

language: cpp
compiler:
  - g++
before_script:
  - cmake ./sources
script:
  - cd sources
  - make
  - cd output
  - ./vcdMaker
