sudo: required
dist: trusty

language: python

python:
  - "3.5"
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - txt2man

before_script:
  - git submodule init
  - git submodule update
  - cd ./sources
  - export CC=gcc-6
  - export CXX=g++-6
  - cmake .
script:
  - make
  - python --version
  - python ../development/test/comparison_test.py --exec ./output/vcdMaker --testdir ./vcdMaker/test
