sudo: required
dist: trusty

language: cpp
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - txt2man

before_script:
  - cd ./sources
  - ls
  - export CC=g++-6
  - export CXX=g++-6
  - $CXX --version
  - cmake .
script:
  - make
  - ./output/vcdMaker
