#The initial configuration came from the article: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

sudo: required
dist: trusty

language: python

python:
  - "3.5"
  
git:
  submodules: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - txt2man

before_script:
  - git submodule update --init --recursive
  - cd ./sources
  - export CC=gcc-6
  - export CXX=g++-6
  - cmake .
  
script:
  - make
  - python --version
  - python ../development/test/comparison_test.py --exec ./output/vcdMaker --testdir ./vcdMaker/test
