#The initial configuration came from the article: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

sudo: required
dist: trusty

python:
  - "3.5"

#Disable the default Travis submodule behavior.
git:
  submodules: false
  
addons:
  apt:

    packages:
    - gcc-6
    - g++-6
    - txt2man

before_script:
  - git submodule update --init --recursive
  - cd ./sources
  - export CC=gcc-6
  - export CXX=g++-6
  
script:
  - cmake .
  - make
  - make comparisonTest
