#The initial configuration came from the article: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/

sudo: required
dist: trusty

python:
  - "3.5"

#Disable the default Travis submodule behavior.
git:
  submodules: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - txt2man
    - lcov
    
# Blocklist - branches not to be built. RegEx is allowed.
branches:
  except:
  - r2_release

# Safelist - branches to be built.
branches:
  only:
  - master

before_script:
  - cd ./sources
  - export CC=gcc-6
  - export CXX=g++-6
  
script:
  - ls /usr/bin | grep gcov
  - lcov --version
  - gcov-8 --version
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 0
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-8 100
  - sudo update-alternatives --query gcov
  - sudo update-alternatives --auto gcov
  - gcov --version
